CREATE TABLE [dbo].[Sys_Requests] (
    [request_id]                      INT             IDENTITY (1, 1) NOT NULL,
    [request_dependency]              INT             CONSTRAINT [DF_Sys_Requests_request_dependency] DEFAULT ('') NOT NULL,
    [request_createduserid]           VARCHAR (10)    CONSTRAINT [DF_sys_requests_request_createduserid] DEFAULT ('') NOT NULL,
    [request_date]                    DATETIME        NOT NULL,
    [request_requestedby]             VARCHAR (50)    CONSTRAINT [DF_sys_request_stakeholder_name] DEFAULT ('') NOT NULL,
    [request_email]                   VARCHAR (50)    CONSTRAINT [DF_sys_request_stakeholder_email] DEFAULT ('') NOT NULL,
    [request_appComponent_ID]         INT             CONSTRAINT [DF_sys_request_request_sitename] DEFAULT ('') NOT NULL,
    [request_SRType_ID]               INT             CONSTRAINT [DF_sys_requests_project_type] DEFAULT ('') NULL,
    [project_description]             TEXT            CONSTRAINT [DF_sys_request_project_description] DEFAULT ('') NOT NULL,
    [Request_Environment_ID]          INT             CONSTRAINT [DF_sys_request_project_keyfeatures] DEFAULT ('') NOT NULL,
    [project_proposeddate]            DATETIME        CONSTRAINT [DF_sys_requests_project_proposeddate] DEFAULT ('') NULL,
    [project_status]                  VARCHAR (30)    CONSTRAINT [DF_sys_request_project_status] DEFAULT ('') NOT NULL,
    [request_Project_ID]              INT             CONSTRAINT [DF_sys_requests_project_name] DEFAULT ('') NOT NULL,
    [project_assigned]                VARCHAR (10)    CONSTRAINT [DF_sys_requests_project_testingduedate1_1] DEFAULT ('') NOT NULL,
    [project_modifieduserid]          VARCHAR (10)    CONSTRAINT [DF_sys_requests_project_modifieduserid] DEFAULT ('') NOT NULL,
    [project_modifieddate]            DATETIME        NULL,
    [request_Severity_ID]             INT             CONSTRAINT [DF_Sys_Requests_request_Severity_ID] DEFAULT ('') NOT NULL,
    [Request_Category_Id]             INT             CONSTRAINT [DF_Sys_Requests_Request_Category_Id] DEFAULT ('') NOT NULL,
    [Request_AccountName]             VARCHAR (400)   CONSTRAINT [DF_Sys_Requests_Request_AccountName_1] DEFAULT ('') NULL,
    [Request_Country]                 INT             CONSTRAINT [DF_Sys_Requests_Request_Country_1] DEFAULT ((0)) NOT NULL,
    [Request_Budget]                  VARCHAR (100)   CONSTRAINT [DF_Sys_Requests_Request_Budget_1] DEFAULT ('') NOT NULL,
    [Request_Currency]                INT             CONSTRAINT [DF_Sys_Requests_Request_Currency_1] DEFAULT ((0)) NOT NULL,
    [Request_SalesStatus]             VARCHAR (50)    CONSTRAINT [DF_Sys_Requests_Request_SalesStatus_1] DEFAULT ('') NOT NULL,
    [Request_SalesCloseComments]      VARCHAR (8000)  CONSTRAINT [DF_Sys_Requests_Request_SalesCloseComments_1] DEFAULT ('') NOT NULL,
    [Request_BudgetKnown]             VARCHAR (50)    CONSTRAINT [DF_Sys_Requests_Request_BudgetKnown_1] DEFAULT ('') NOT NULL,
    [request_channelId]               INT             DEFAULT ((0)) NOT NULL,
    [Request_Code]                    VARCHAR (200)   DEFAULT ('') NOT NULL,
    [request_SRType_OtherText]        VARCHAR (MAX)   DEFAULT ('') NOT NULL,
    [Request_StatusId]                INT             DEFAULT ((0)) NOT NULL,
    [request_IndustryID]              INT             DEFAULT ((0)) NOT NULL,
    [request_CustCategID]             INT             DEFAULT ((0)) NOT NULL,
    [request_SalesStageID]            INT             DEFAULT ((0)) NOT NULL,
    [request_IsProductCompany]        BIT             DEFAULT ((0)) NOT NULL,
    [Request_Environment_OthersText]  VARCHAR (500)   DEFAULT ('') NOT NULL,
    [Request_DealAmount]              NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [Request_DealCurrencyID]          INT             DEFAULT ((0)) NOT NULL,
    [request_NotificationHrs]         INT             DEFAULT ((240)) NOT NULL,
    [request_IsLeadOrOpportunity]     VARCHAR (50)    DEFAULT ('') NOT NULL,
    [request_EndCustomerName]         VARCHAR (200)   DEFAULT ('') NOT NULL,
    [Request_SalesStageRatingID]      INT             DEFAULT ((0)) NOT NULL,
    [Request_IsJDattached]            BIT             DEFAULT ((0)) NULL,
    [Request_CustomerGeography]       VARCHAR (100)   DEFAULT ('') NULL,
    [Request_TurnoverAmount]          NUMERIC (22, 5) DEFAULT ((0.0)) NULL,
    [Request_TurnoverUnit]            VARCHAR (50)    DEFAULT ('') NULL,
    [Request_TurnoverCurrency]        INT             DEFAULT ((0)) NULL,
    [Request_EmployeeCount]           VARCHAR (100)   DEFAULT ((0)) NULL,
    [Request_PracticeHead]            VARCHAR (100)   DEFAULT ('') NOT NULL,
    [request_EngagementModel]         VARCHAR (500)   DEFAULT ('') NOT NULL,
    [Request_PrimRegionId]            INT             DEFAULT ((0)) NOT NULL,
    [Request_SecRegionId]             INT             DEFAULT ((0)) NOT NULL,
    [request_IsPresalesActive]        BIT             DEFAULT ((0)) NOT NULL,
    [request_TechnicalCordinator]     VARCHAR (100)   DEFAULT ('') NOT NULL,
    [request_PresalesCordinatorDate]  DATETIME        DEFAULT ('') NOT NULL,
    [request_TechnicalCordinatorDate] DATETIME        DEFAULT ('') NOT NULL,
    [request_CRMLeadID]               VARCHAR (20)    DEFAULT ('') NOT NULL,
    [PresalesDocumentStatusID]        INT             NULL,
    [request_OrganizationTypeID]      INT             NULL,
    [request_Customer_id]             INT             NULL,
    [request_IsExisting_Account]      INT             NULL,
    [LastUpdatedDate]                 DATETIME        NULL,
    [LastUpdatedBy]                   INT             DEFAULT ((0)) NOT NULL,
    [request_IsNewOrExistAccount]     VARCHAR (100)   DEFAULT ('') NOT NULL,
    [request_CustWebsite]             VARCHAR (500)   DEFAULT ('') NOT NULL,
    [Request_AnnualRevenueId]         INT             DEFAULT ((0)) NOT NULL,
    [request_CustPrimContactTitle]    VARCHAR (100)   DEFAULT ('') NOT NULL,
    [request_CustPrimContactName]     VARCHAR (500)   DEFAULT ('') NOT NULL,
    [request_CustPrimContactJobTitle] VARCHAR (500)   DEFAULT ('') NOT NULL,
    [request_CRMopportunityID]        VARCHAR (100)   DEFAULT ('') NOT NULL,
    [Request_Type]                    INT             DEFAULT ((1)) NOT NULL,
    [request_salesforceOwnerID]       NVARCHAR (100)  DEFAULT ('') NOT NULL,
    [Request_LeadOpportunityName]     NVARCHAR (250)  DEFAULT ('') NOT NULL,
    [request_SubDomainID]             INT             DEFAULT ((0)) NOT NULL,
    [request_SubLobID]                INT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Sys_Requests] PRIMARY KEY CLUSTERED ([request_id] ASC) WITH (FILLFACTOR = 90)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'This column for separation of Lead and opportunity(1) and query(2)', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Sys_Requests', @level2type = N'COLUMN', @level2name = N'Request_Type';

